require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  Exclude:
    - app/channels/application_cable/channel.rb
    - app/channels/application_cable/connection.rb
    - app/controllers/application_controller.rb
    - app/controllers/catalog_controller.rb
    - app/helpers/application_helper.rb
    - app/jobs/application_job.rb
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - app/models/solr_document.rb
    - app/models/user.rb
  TargetRubyVersion: 2.5
  NewCops: enable
Layout/ExtraSpacing:
  Exclude:
    - lib/tasks/data/config/*
Metrics/BlockLength:
  Exclude:
    - lib/tasks/data.rake
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - indexer
Style/MixinUsage:
  Exclude:
    - lib/tasks/data/config/*.rb